CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(10) UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL,
    description VARCHAR(100),
    price MONEY,
    category VARCHAR(20),
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart ( 
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);   

CREATE TABLE cart_item (
    id SERIAL PRIMARY KEY,
    quantity INT DEFAULT 1,
    cart_id INT REFERENCES cart(id) NOT NULL ON DELETE CASCADE,
    prod_id INT REFERENCES products(id) NOT NULL ON DELETE CASCADE,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_detail (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    total DECIMAL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_item (
    id SERIAL PRIMARY KEY,
    order_id INT REFERENCES order_detail(id) ON DELETE CASCADE,
    prod_id INT REFERENCES products(id) ON DELETE CASCADE,
    quantity INT DEFAULT 1,
    price MONEY NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- INSERT INTO users(username, email, password) VALUES('Luu Bega', 'luu@bega.com', 'asdf1234');
-- INSERT INTO products(name, description) VALUES('jordans', 'latest pair of jordans');